### ISSUE TITLE
High-resolution screen support

### ISSUE THREAD

**Issue by DavidLee528** [NSTerminal/terminal#1]
I successfully build the terminal on my visual studio 2022, but the font size is too small to fit my 4k monitor, hoping to fix this little problem. 
![image](https://user-images.githubusercontent.com/35065046/161939401-5c569f43-d751-4028-9c6f-51784e12e7c2.png)

**Comment by AidanSun05** [comment]
In the settings file (`app/settings.hpp`) there is a `fontSize` variable. Try increasing it to enlarge the application font size.

(Since settings are not saved/loaded by the app yet, you will have to rebuild after modifying any settings.)

**Comment by DavidLee528** [comment]
> In the settings file (`app/settings.hpp`) there is a `fontSize` variable. Try increasing it to enlarge the application font size.
> 
> (Since settings are not saved/loaded by the app yet, you will have to rebuild after modifying any settings.)

Great thanks to you, that is helpful to beginners like me. :)
