### ISSUE TITLE
[JOSS Review] WhaleConnect does not install in MacOS Sonoma 14.1.1

### ISSUE THREAD

**Issue by harshadjs** [NSTerminal/terminal#3]
### WhaleConnect Build Info

N/A

### Operating System and Architecture

MacOS Sonoma 14.1.1

### Bug Description

I tried to install WhaleConnect on MacOS 14.1.1 sonoma, but got an error that this WhaleConnect cannot be installed on this version. I'll try tomorrow with updated OS, but please look into this.

<img width="500" alt="Screenshot 2024-07-27 at 10 08 56 PM" src="https://github.com/user-attachments/assets/ce7c55b9-4018-48df-b36a-7ccf7f9f28ac">

**Comment by AidanSun05** [comment]
Are you using a Mac with an Intel chip or an Apple Silicon chip? Currently, WhaleConnect only supports the latter since it is built on the `macos-latest` GitHub Actions runner, which runs on Arm64.

**Comment by AidanSun05** [comment]
Can you please download the [v1.0.1 release](https://github.com/WhaleConnect/whaleconnect/releases/tag/v1.0.1) and try again? This version improves compatibility with some older versions of macOS (including 14.1) and fixes a few bugs.
