### ISSUE TITLE
[JOSS REVIEW] referencing of diagram in paper

### ISSUE THREAD

**Issue by wob86** [NSTerminal/terminal#4]
### WhaleConnect Build Info

Paper

### Operating System

N/A

### CPU Architecture

N/A

### Bug Description

Paper is well written and diagram is useful but should be referenced (eg see figure 1) rather than see diagram below

@https://github.com/openjournals/joss-reviews/issues/6964

**Comment by AidanSun05** [comment]
Thank you for the suggestion. The sentence referring to the diagram now starts with "Figure 1 presents an architecture diagram..." and uses the `\autoref` command for the reference.

**Comment by wob86** [comment]
Great looks much better
